### ISSUE TITLE
Runtime.HandlerNotFound: Handler 'lambda_handler' missing on module 'handler'

### ISSUE THREAD

**Issue by hyeokju98** [zappa/Zappa#1214]
## Context
when i deploy my django(3.2.6) service with Zappa, if i deploy zappa in local that can work very clearly but when i using github action, it doesn't work and send me log like (Runtime.HandlerNotFound: Handler 'lambda_handler' missing on module 'handler')

I can't catch, "what is wrong did i".

please help me what is wrong with this

## Steps to Reproduce

1. just using github workflow
2. and update zappa service

## Your Environment

* Zappa version used: 0.56.1
* Operating System and Python version: 3.9
* The output of `pip freeze`: 
```
argcomplete==1.9.2
asgiref==3.5.2
base58==0.2.4
boto3==1.26.51
botocore==1.29.51
certifi==2022.12.7
cfn-flip==1.0.4
charset-normalizer==2.1.1
click==8.1.3
Django==3.2.6
django-dotenv==1.4.2
django-s3-storage==0.13.11
djangorestframework==3.12.4
djangorestframework-simplejwt==4.8.0
docutils==0.19
durationpy==0.5
et-xmlfile==1.1.0
future==0.16.0
futures==3.1.1
handler==1.3.0
hjson==3.0.0
idna==3.4
importlib-metadata==4.13.0
jmespath==0.9.3
kappa==0.6.0
lambda-packages==0.16.1
MarkupSafe==2.1.1
mccabe==0.7.0
mysqlclient==2.0.3
openpyxl==3.0.10
placebo==0.9.0
pycodestyle==2.10.0
pycrypto==2.6.1
pycryptodome==3.11.0
pycryptodomex==3.11.0
pyflakes==3.0.1
PyJWT==2.6.0
PyMySQL==1.0.2
python-dateutil==2.6.1
python-dotenv==0.21.0
python-slugify==1.2.4
pytz==2022.6
PyYAML==6.0
requests==2.28.1
s3transfer==0.6.0
six==1.11.0
sqlparse==0.4.3
text-unidecode==1.3
toml==0.9.2
tqdm==4.15.0
troposphere==4.2.0
typing_extensions==4.4.0
Unidecode==1.3.6
urllib3==1.26.13
Werkzeug==0.12
wsgi-request-logger==0.4.6
xlrd==2.0.1
xlwt==1.3.0
zappa==0.56.1
zipp==3.11.0
```
* Link to your project (optional):
* Your `zappa_settings.json`: 
```
{
    "dev": {
        "aws_region": "---",
        "django_settings": "project.settings.local",
        "project_name": "project-serverless",
        "runtime": "python3.9",
        "s3_bucket": "project-serverless-dev",
        "touch":false
        
    },
    "prod": {
        "aws_region": "---",
        "django_settings": "project.settings.prod",
        "project_name": "project-serverless",
        "runtime": "python3.9",
        "s3_bucket": "project-serverless-prod",
        "touch":false
    }
}
```
* My YAML
```
name: Server-admin-serverless-dev-Deply

on:
  push:
    branches: 
    - feature-issue#19
    # - main
    # - feature

jobs: 
  Build: 
    name: build django 
    runs-on: ubuntu-latest 
    steps:
      - name: Make envfile
        uses: SpicyPizza/create-envfile@v1.3
        with:
          envkey_CRYPTO_SECRET_KEY: ${{ secrets.CRYPTO_SECRET_KEY }}
          envkey_DB_NAME_DEV: "${{ secrets.DB_NAME_DEV }}"
          envkey_READ_DB_HOST_PROD: "${{ secrets.READ_DB_HOST_PROD }}"
          envkey_READ_DB_PASSWORD_PROD: "${{ secrets.READ_DB_PASSWORD_PROD }}"
          envkey_READ_DB_PORT_PROD: "${{ secrets.READ_DB_PORT_PROD }}"
          envkey_READ_DB_USER_PROD: "${{ secrets.READ_DB_USER_PROD }}"
          envkey_SOLDOC_SECRET_KEY: "${{ secrets.SOLDOC_SECRET_KEY }}"
          envkey_WRITE_DB_HOST_DEV: "${{ secrets.WRITE_DB_HOST_DEV }}"
          envkey_WRITE_DB_PASSWORD_DEV: "${{ secrets.WRITE_DB_PASSWORD_DEV }}"
          envkey_WRITE_DB_PORT_DEV: "${{ secrets.WRITE_DB_PORT_DEV }}"
          envkey_WRITE_DB_USER_DEV: "${{ secrets.WRITE_DB_USER_DEV }}"
          file_name: .env
          fail_on_empty: false
      - name: AWS configure credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - uses: actions/checkout@v3
      - name: Set up Python 3.9
        uses: actions/setup-python@v1
        with:
          python-version: 3.9
      - name: UPDATE MODEL.PY
        run: |
          python -m venv venv
      - name: update prod with zappa
        if: ${{ github.ref_name == 'main'}}
        env:
          VIRTUAL_ENV: ./venv
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          source venv/bin/activate
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          zappa update prod 
      - name: update dev with zappa
        if: ${{ github.ref_name == 'feature-issue#19'}}
        env:
          VIRTUAL_ENV: ./venv
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          source venv/bin/activate
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          zappa update dev 
```
